Kelompok-2-Capstone-Alterra-Academy/flutter-repo

lib/widgets/card/card_course_taken.dart
lib/widgets/card/card_live_session.dart
lib/widgets/card/card_task_list.dart

This PR implement live session card, task card, course taken card for dashboard after having a course
Link Trello:
https://trello.com/c/FJ6H0cQ4

[SB-Dashboard-06] Adding 3 Card for dashboard after have course

---

lib/views/screen/course/course_taken_list_screen.dart
lib/views/screen/course/module/module_list_screen.dart
lib/views/screen/history/history_transaction_screen.dart
lib/views/screen/home/home_screen.dart
lib/views/screen/mentor/chat_mentor_screen.dart
lib/views/screen/mentor/search_chat_screen.dart
lib/views/screen/profile/profile_screen.dart
lib/widgets/bottom_navigation_bar/bottom_navigation_bar.dart

This PR is enhancement logic bottom nav bar. If you want to change page without use bottom nav bar, please follow this implementation to change current active bottom nav bar. 
CC @KyrizP @RoyalWeaboo @NalendraKian @ahmadabidb

[SB-Profile-06] Enhance Bottom Nav Bar

---

lib/models/service/profile_api.dart
lib/models/user_model.dart
lib/views/screen/auth/forgot_password/forgot_password_view_model.dart
lib/views/screen/auth/login/login_screen.dart
lib/views/screen/auth/login/login_view_model.dart
lib/views/screen/course/course_taken_list_screen.dart
lib/views/screen/course/module/module_list_screen.dart
lib/views/screen/edit_profile/edit_profile_screen.dart
lib/views/screen/edit_profile/edit_profile_view_model.dart
lib/views/screen/history/history_transaction_screen.dart
lib/views/screen/home/home_screen.dart
lib/views/screen/mentor/chat_mentor_screen.dart
lib/views/screen/mentor/search_chat_screen.dart
lib/views/screen/profile/profile_screen.dart
lib/views/screen/profile/profile_view_model.dart
lib/widgets/bottom_navigation_bar/bottom_navigation_bar.dart
pubspec.lock
pubspec.yaml

This PR is integrate API profile and edit profile

[SB-Profile-05] Integrate API

---

lib/models/service/auth_api.dart
lib/models/service/profile_api.dart
lib/models/user_model.dart
lib/utils/constant/constant.dart
lib/views/screen/auth/forgot_password/forgot_password_view_model.dart
lib/views/screen/auth/forgot_password/otp_verification/otp_verification_screen.dart
lib/views/screen/auth/forgot_password/reset_password/reset_password.dart
lib/views/screen/auth/login/login_screen.dart
lib/views/screen/auth/login/login_view_model.dart
lib/views/screen/course/course_taken_list_screen.dart
lib/views/screen/course/module/module_list_screen.dart
lib/views/screen/edit_profile/edit_profile_screen.dart
lib/views/screen/edit_profile/edit_profile_view_model.dart
lib/views/screen/history/history_transaction_screen.dart
lib/views/screen/home/home_screen.dart
lib/views/screen/mentor/chat_mentor_screen.dart
lib/views/screen/mentor/search_chat_screen.dart
lib/views/screen/profile/profile_screen.dart
lib/views/screen/profile/profile_view_model.dart
lib/widgets/bottom_navigation_bar/bottom_navigation_bar.dart
pubspec.lock
pubspec.yaml

This PR fixing integration API forgot password

[SB Forgot Password] Integrate API

---

lib/models/schedule_model.dart
lib/models/service/schedule_api.dart
lib/utils/constant/list_schedule_course.dart
lib/views/screen/live_session/detail_schadule_screen.dart
lib/views/screen/live_session/schedule_course_screen.dart
lib/views/screen/live_session/schedule_view_model.dart
lib/views/screen/live_session/schedule_web_view.dart
lib/widgets/card/card_live_session.dart

This PR implements dummy API for Live Session Detail Screen with Dummy API.
Trello Card Link : https://trello.com/c/ScllK42d

[SB-Live Session Detail-02] Integrate with Dummy API 

---

lib/main.dart
lib/models/module_details_model.dart
lib/models/service/module_api.dart
lib/views/screen/course/module/detail/module_detail_video_screen.dart
lib/views/screen/course/module/module_list_screen.dart
lib/views/view_model/course/module_view_model.dart
lib/widgets/module_course/module_section_card.dart

This PR implements dummy API for Module Detail Video Screen. Real API will be implemented once the endpoint made by Backend Teams.
Trello Card Link : https://trello.com/c/Nr2llGhv

[SB-Module Detail Video-02] Integrate with Dummy API

---

lib/main.dart
lib/models/module_details_model.dart
lib/models/service/module_api.dart
lib/views/screen/course/module/detail/module_detail_task_screen.dart
lib/views/screen/course/module/detail/module_detail_video_screen.dart
lib/views/screen/course/module/module_list_screen.dart
lib/views/view_model/course/module_view_model.dart
lib/widgets/module_course/module_section_card.dart

This PR implements dummy API for Module Detail Task Screen. Real API will be implemented once the endpoint made by Backend Teams.
Trello Card Link : https://trello.com/c/2Ym10Oq6

[SB-Module Detail Task-02] Integrate with Dummy API

---

lib/main.dart
lib/models/certificate_model.dart
lib/models/module_details_model.dart
lib/models/service/certificate_api.dart
lib/models/service/module_api.dart
lib/views/screen/course/module/detail/module_detail_task_screen.dart
lib/views/screen/course/module/detail/module_detail_video_screen.dart
lib/views/screen/course/module/module_list_screen.dart
lib/views/view_model/course/certificate_view_model.dart
lib/views/view_model/course/module_view_model.dart
lib/widgets/course/course_certificate.dart
lib/widgets/module_course/module_section_card.dart

This PR implements dummy API for Module Certificate Screen. Real API will be implemented once the endpoint made by Backend Teams.
Trello Card Link : https://trello.com/c/eE7KztCo

[SB-Certificate-02] Integrate with Dummy API

---

lib/main.dart
lib/models/certificate_model.dart
lib/models/module_details_model.dart
lib/models/service/certificate_api.dart
lib/models/service/module_api.dart
lib/views/screen/course/module/detail/module_detail_task_screen.dart
lib/views/screen/course/module/detail/module_detail_video_screen.dart
lib/views/screen/course/module/module_list_quiz_screen.dart
lib/views/screen/course/module/module_list_screen.dart
lib/views/screen/course/module/module_task_list_screen.dart
lib/views/view_model/course/certificate_view_model.dart
lib/views/view_model/course/module_view_model.dart
lib/widgets/course/course_certificate.dart
lib/widgets/module_course/module_section_card.dart

This PR implements dummy API for Module Quiz List Screen. Real API will be implemented once the endpoint made by Backend Teams.
Trello Card Link : https://trello.com/c/TB08MpZs

[SB-Quiz List-02] Integrate with Dummy API

---

lib/views/screen/auth/forgot_password/otp_verification/otp_verification_screen.dart
lib/views/screen/auth/register/account_verification/account_verification.dart
lib/views/screen/auth/register/main/register_screen.dart

This Pr is Fixing Auth Validation

[Fix Auth Validation] Fixing Auth Validation

---

lib/models/new_module_list_model.dart
lib/views/screen/course/module/module_list_quiz_screen.dart
lib/views/screen/course/module/module_list_screen.dart
lib/views/view_model/course/course_taken_view_model.dart
lib/views/view_model/course/module_view_model.dart
lib/widgets/course/filter_course_taken.dart
lib/widgets/module_course/module_card.dart

This PR fixed filter for course taken by major.
No Trello Card

[SB-Course Taken List-02] Fixed Filter Course Taken

---

lib/models/new_module_list_model.dart
lib/models/service/module_api.dart
lib/views/screen/auth/login/login_screen.dart
lib/views/screen/course/module/detail/module_detail_ppt_screen.dart
lib/views/screen/course/module/detail/module_detail_video_screen.dart
lib/views/screen/course/module/detail/module_quiz_detail_screen.dart
lib/views/screen/course/module/module_list_quiz_screen.dart
lib/views/screen/course/module/module_list_screen.dart
lib/views/screen/course/module/module_send_task_screen.dart
lib/views/view_model/course/course_taken_view_model.dart
lib/views/view_model/course/module_view_model.dart
lib/widgets/course/filter_course_taken.dart
lib/widgets/course/finished_course_taken_list.dart
lib/widgets/course/ongoing_course_taken_list.dart
lib/widgets/course/review_dialog.dart
lib/widgets/module_course/module_card.dart

This PR implements fix section and progress bug that already expected before.
No Trello Card

[SB-Course Taken List-02] Fixed Progress & Section in Course Taken Screen

---

lib/models/new_module_list_model.dart
lib/models/service/module_api.dart
lib/utils/preferences/preferences_utils.dart
lib/views/screen/auth/login/login_screen.dart
lib/views/screen/course/module/detail/module_detail_ppt_screen.dart
lib/views/screen/course/module/detail/module_detail_video_screen.dart
lib/views/screen/course/module/detail/module_quiz_detail_screen.dart
lib/views/screen/course/module/module_list_quiz_screen.dart
lib/views/screen/course/module/module_list_screen.dart
lib/views/screen/course/module/module_send_task_screen.dart
lib/views/view_model/course/course_taken_view_model.dart
lib/views/view_model/course/module_view_model.dart
lib/widgets/course/filter_course_taken.dart
lib/widgets/course/finished_course_taken_list.dart
lib/widgets/course/ongoing_course_taken_list.dart
lib/widgets/course/review_dialog.dart
lib/widgets/module_course/module_card.dart
lib/widgets/module_course/module_quiz_card.dart

This PR implements Course Progress Feature (bug expected and will be fixed after more data is available).
No Trello Card

[SB-Course Taken List-02] Added Course Progress & Section in Course Taken Screen

---

lib/main.dart
lib/utils/http/http_utils.dart
lib/views/screen/course/module/detail/module_detail_task_screen.dart
lib/views/screen/course/module/detail/module_quiz_detail_screen.dart
lib/views/screen/course/module/module_list_quiz_screen.dart
lib/views/screen/course/module/module_list_screen.dart
lib/widgets/course/ongoing_course_taken_list.dart
lib/widgets/module_course/module_button.dart
lib/widgets/module_course/module_card.dart
lib/widgets/module_course/module_quiz_card.dart

This PR implement revision and bug fix for Detail Task Screen and Send Task Screen (now with google docs)
No Trello Card

[SB-Course Taken List-02] Fixed Detail & Send Task Feature

---

lib/models/mentor.dart
lib/models/service/course_api.dart
lib/models/service/mentor_api.dart
lib/views/screen/home/home_screen.dart
lib/views/screen/home/home_view_model.dart
lib/views/screen/profile/profile_screen.dart
lib/views/screen/profile/profile_view_model.dart
lib/views/screen/splash_welcome/splash_welcome_screen.dart
lib/widgets/card/card_mentor.dart
lib/widgets/carousel/carousel_component.dart

This PR is implement
1. fixing UI for all case 
2. integrate api mentor 
3. splash to home screen 
there are several UI not integrate yet and used dummy

[SB-Dashboard-07] Fixing UI

---

lib/models/mentor.dart
lib/models/service/course_api.dart
lib/models/service/mentor_api.dart
lib/models/service/profile_api.dart
lib/models/user_model.dart
lib/views/screen/home/home_screen.dart
lib/views/screen/home/home_view_model.dart
lib/views/screen/profile/profile_screen.dart
lib/views/screen/profile/profile_view_model.dart
lib/views/screen/splash_welcome/splash_welcome_screen.dart
lib/widgets/card/card_mentor.dart
lib/widgets/carousel/carousel_component.dart

This PR enhancement edit profile API

[SB-Edit-Profile-05] Edit endpoint Profile

---

lib/models/mentor.dart
lib/models/service/course_api.dart
lib/models/service/mentor_api.dart
lib/models/service/profile_api.dart
lib/models/user_model.dart
lib/views/screen/auth/register/account_verification/account_verification.dart
lib/views/screen/home/home_screen.dart
lib/views/screen/home/home_view_model.dart
lib/views/screen/profile/profile_screen.dart
lib/views/screen/profile/profile_view_model.dart
lib/views/screen/splash_welcome/splash_welcome_screen.dart
lib/widgets/card/card_mentor.dart
lib/widgets/carousel/carousel_component.dart

This PR is add focus node on account verification

[SB-Register-07] Add Focus Node

---

lib/views/screen/course/module/module_send_task_screen.dart
lib/views/view_model/course/task_view_model.dart
lib/widgets/course/ongoing_course_taken_list.dart

This PR implement bug fix for Send Task where the response always return code 500.
No Trello Card

[SB-Send Task-03] Fixed Failed to Send Task

---

lib/views/screen/course/module/detail/module_detail_task_screen.dart
lib/views/view_model/course/task_view_model.dart

This PR implement minor revision in Detail Task Page.
Trello Card Link : https://trello.com/c/2Ym10Oq6

[SB-Module Detail Task-02] Minor Revision on Detail Task Page

---

lib/utils/constant/list_schedule_course.dart
lib/views/screen/history/history_transaction_view_model.dart
lib/views/screen/live_session/detail_schadule_screen.dart

This PR implements dummy API for Live Session Detail Screen with Dummy API.
Trello Card Link : https://trello.com/c/ScllK42d

[SB-Live Session Detail-04] Integrate with Dummy API

---

lib/models/service/course_api.dart
lib/models/service/mentor_api.dart
lib/models/user_model.dart
lib/views/screen/auth/login/login_screen.dart
lib/views/screen/course/module/module_list_screen.dart
lib/views/screen/home/home_screen.dart
lib/views/screen/home/home_view_model.dart
lib/views/screen/profile/profile_screen.dart
lib/views/view_model/sell_course/sell_course_view_model.dart
lib/widgets/button/button_text.dart
lib/widgets/card/card_course_taken.dart
lib/widgets/card/card_mentor.dart
lib/widgets/carousel/carousel_component.dart

Enhance Ui dashboard and integrate API

[SB-Dashboard-08] Enhance UI Dashboard

---

lib/models/ppt_model.dart
lib/views/screen/course/module/detail/module_detail_ppt_screen.dart
lib/views/screen/course/module/detail/module_detail_task_screen.dart
lib/views/screen/course/module/module_list_screen.dart
lib/views/screen/course/module/module_send_task_screen.dart
lib/widgets/module_course/module_card.dart

This PR implement revision on module content such as course name, section name and description on PPT & Send Task Screen
No Trello Card

[SB-Module Detail PPT-02] & [SB-Send Task-02] Revision on Module Content

---

lib/views/screen/course/module/module_list_screen.dart
lib/widgets/module_course/module_button.dart

This PR implement fix bug for check null for empty task list
No Trello Card

[SB-Module Task Detail-02] Bug Fix on check null for empty tasks list

---

lib/models/post_feed_model.dart
lib/models/reply_model.dart
lib/models/service/post_feed_api.dart
lib/utils/constant/list_post_feed.dart
lib/views/screen/post_feed/post_detail_screen.dart
lib/views/screen/post_feed/post_feed_screen.dart
lib/views/screen/post_feed/post_feed_view_model.dart
lib/widgets/post_feed/post_feed.dart

This PR implements dummy API for Post Feed Screen with Dummy API.
Trello Card Link :https://trello.com/c/w3SdojWZ

[SB-Post Feed-04] Integrate with Dummy API

---

lib/utils/color/color.dart
lib/views/screen/course/module/detail/module_detail_task_screen.dart
lib/views/screen/course/module/detail/module_quiz_detail_screen.dart
lib/views/screen/course/module/module_list_quiz_screen.dart
lib/views/screen/course/module/module_send_task_screen.dart
lib/views/view_model/course/task_view_model.dart
lib/widgets/course/ongoing_course_taken_list.dart
lib/widgets/course/review_dialog.dart
lib/widgets/module_course/module_quiz_detail_done_dialog.dart
lib/widgets/module_course/module_send_task_done_dialog.dart

This PR implement revision on dialogs Navigation and Fixed Rating Bug where it always send 0 rating.
No Trello Card

[SB-Send Rating-02] Revision on Dialog  Navigation and Fixed Rating Bug.

---

lib/models/service/profile_api.dart
lib/models/user_model.dart
lib/utils/constant/user_mock.dart
lib/views/screen/edit_profile/edit_profile_screen.dart
lib/views/screen/edit_profile/edit_profile_view_model.dart
lib/views/screen/profile/profile_view_model.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

Integrate API Upload Photo and enhance edit profile

[SB-Edit Profile 06] Integrate API Upload Photo

---

lib/views/screen/mentor/chat_mentor_screen.dart

this pr is fixing ui in chat mentor screen

[SB-Chat-Mentor-02] Fix UI in chat mentor screen

---

lib/views/view_model/course/course_taken_view_model.dart
lib/views/view_model/sell_course/sell_course_view_model.dart

This PR implement fix filter bug in sell course & course taken screen where no data shown when user immediately click save button with no filter selected
No Trello Card

[SB-Course For Sale Filter-02] & [SB-Course Taken List-02] Fixed Filter Bug

---

lib/models/service/course_api.dart
lib/views/screen/home/home_screen.dart
lib/views/screen/post_feed/post_detail_screen.dart
lib/views/screen/sell_course/sell_course_detail_screen.dart
lib/views/screen/sell_course/sell_course_screen.dart
lib/widgets/card/card_course_taken.dart
lib/widgets/post_feed/post_feed.dart

this PR is implement fixing dashboard card, blocking for course for sale

[SB-Dashboard-09] fixing dashboard card, blocking for course for sale

---

lib/views/screen/profile/profile_screen.dart

this PR is fixing profile screen that dont show users profile screen from API

[SB-Profile-07] Fixing photo profile on profile screen

---

lib/views/screen/auth/forgot_password/reset_password/reset_password.dart
lib/views/screen/sell_course/sell_course_detail_screen.dart

this PR is fixing blocker for take course, to make user cant take the same course and fixing forgot password popup

[SB-Take-Course-02] Fix Blocker for take course and fix reset password popup

---

lib/views/screen/course/module/module_list_screen.dart

This is PR is for fixing conditioning to show the certificate screen of a course

[SB-Certificate-Screen] Fixing condition for Certificate Screen
